      FUNCTION DGAMMP(A,X)
      DOUBLE PRECISION A,X,DGAMMP,DGLN,DGAMMCF
      IF(X.LT.0.D0.OR.A.LE.0.D0) STOP(' ')
      IF(X.LT.A+1.D0)THEN
        CALL DGSER(DGAMMP,A,X,DGLN)
      ELSE
        CALL DGCF(DGAMMCF,A,X,DGLN)
        DGAMMP=1.D0-DGAMMCF
      ENDIF
      RETURN
      END
